services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  nginx:
   depends_on: 
     - backend
     - frontend
     - order-process
   restart: always
   build: 
     dockerfile: Dockerfile.dev
     context: ./nginx 
   ports:
    - "3050:80"
  backend:
   build: 
     dockerfile: Dockerfile.dev
     context: ./backend
   volumes: 
     - /app/node_modules
     - ./backend:/app
   environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password 
      - PGPORT=5432
  frontend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes: 
      - /app/node_modules
      - ./frontend:/app
  worker: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app     
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379    
  order-process:
    build:
      dockerfile: Dockerfile.dev
      context: ./order-process
    volumes:
      - ./order-process:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres_password

