services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: "redis:latest"
  nginx:
   depends_on: 
     - backend
     - frontend
   restart: always
   build: 
     dockerfile: Dockerfile.dev
     context: ./nginx 
   ports:
    - "3050:80"
  backend:
   build: 
     dockerfile: Dockerfile.dev
     context: ./backend
   volumes: 
     - /app/node_modules
     - ./backend:/app
   environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password 
      - PGPORT=5432
  frontend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes: 
      - /app/node_modules
      - ./frontend:/app
  worker: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes: 
      - /app/node_modules
      - ./worker:/app     
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379    

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro